# Generated by Django 4.2.4 on 2023-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
